Data_Preparation:
  test_size: 0.25
  random_state: 42

Train:
  Random_Forest:
    n_estimators: 500
    criterion: 'squared_error'
    max_depth: 13
    min_samples_split: 9
    min_samples_leaf: 2
    max_samples: 0.8063673526197067
    verbose: 1
    n_jobs: -1

  
  LightGBM:
    n_estimators: 196
    max_depth: 40
    learning_rate: 0.12234435854395157
    subsample: 0.8162213724048168
    min_child_weight: 6
    min_split_gain: 0.004604680609280751
    reg_lambda: 1.2202379097947
    n_jobs: -1